image: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: 'Setting Build Environment'
        script:
          - apt update
          - apt install -y git curl zip unzip tar cmake build-essential libxmu-dev libxi-dev libgl-dev libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libboost-all-dev liblpsolve55-dev lp-solve libeigen3-dev
          - echo "Setting up vcpkg into local..."
          - git clone https://github.com/Microsoft/vcpkg.git /vcpkg
          - sh /vcpkg/bootstrap-vcpkg.sh
          - export CMAKE_MAKE_PROGRAM="/usr/bin/make"
          - export CMAKE_CXX_COMPILER="/usr/bin/g++"
          - git submodule update --recursive --init
          - mkdir build
          - cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE="/vcpkg/scripts/buildsystems/vcpkg.cmake"
          - make -C build/ -j8
        artifacts:
          - build/**
    - step:
        name: 'Running Tests'
        script:
          - apt update
          - apt install -y cmake
          - cd build/
          - ctest --verbose
    - step:
        name: 'Check Format'
        script:
          - apt update
          - apt install -y clang-format
          - find src/ -iname *.h -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
          - find include/ -iname *.h -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
        artifacts:
          download: false